#!/usr/bin/python3
# -*- coding: utf-8 -*-
import sys
import os

# Ensure src/ is in sys.path
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "src"))

from unicorcli import main  # Import from `unicorcli.py`

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
