logging_level: "INFO"
misp_servers:
 - domain: "http://misp-demo.es.net/"
   api_key: "My_MISP_API_key"
   verify_ssl: True
   debug: False 
   # misp.search() arguments
   args:
     enforce_warninglist: True 
   periods:
     generic:
       delta:
         days: 50
     tags:
     - names:
         - "apt"
         - "tlp:amber"
       delta: 
         days: 365 

correlation:
  input_dir: /var/unicor/matches # use this if no files are defined from commmand line
  output_dir: /var/unicor/alerts
  archive_dir: /var/unicor/archive # use this as input for looking back
  alerts_database: /var/unicor/alerts_db.txt
  alerts_database_max_size: 300 #This is how many alerts we keep in the buffer before re-notifying  
  malicious_domains_file: /var/unicor/misp_domains.txt
  malicious_ips_file: /var/unicor/misp_ips.txt

alerting:
  # method: slack or email
#  slack: 
#     slack_hook: "https://hooks.slack.com/services/..."
#  email:
#    from: "security@your_org.net"
#    subject: "[Unicor] your_org DNS alert"
#    summary_to: "me@your_org.net"
#    server: "localhost"
#   port: 25
#    mappings:
#      - client_id: client_1
#        contact: client_1_sec_team@domain.tld

